#!/bin/bash
set -e  # 遇到任何命令失败时立即终止脚本

SHARE_DIR="${TRIM_APPDEST_VOL}/@appshare/${TRIM_APPNAME}"
LOG_DIR="${SHARE_DIR}/logs"
LOG_FILE="${LOG_DIR}/cmd.log"
CFG_FILE="${SHARE_DIR}/smartdns.conf"
DATA_DIR="${TRIM_PKGVAR}/data"

log_msg() {
    if [ ! -d "${LOG_DIR}" ]; then
        mkdir -p "${LOG_DIR}" || alarm_and_exit "无法创建日志目录: ${LOG_DIR}"
        echo "$(date '+%Y-%m-%d %H:%M:%S') - 创建日志目录: ${LOG_DIR}" >> "${LOG_FILE}"
    fi
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "${LOG_FILE}"
}

alarm_and_exit() {
    log_msg "$1"
    echo "$1" > "${TRIM_TEMP_LOGFILE}"
    exit 1
}

str_trim() {
    local str="$1"
    str="${str#"${str%%[![:space:]]*}"}"   # 去除首空格
    str="${str%"${str##*[![:space:]]}"}"  # 去除尾空格
    echo "$str"
}

check_port_in_use() {
    local port=$1
    local exclude_process=$2
    if command -v ss >/dev/null 2>&1; then
        if [ -n "$exclude_process" ]; then
            ss -tlnp | grep -q ":$port " | grep -v "$exclude_process"
        else
            ss -tln | grep -q ":$port "
        fi
    elif command -v netstat >/dev/null 2>&1; then
        if [ -n "$exclude_process" ]; then
            netstat -tlnp | grep -q ":$port " | grep -v "$exclude_process"
        else
            netstat -tln | grep -q ":$port "
        fi
    else
        return 1
    fi
}

update_config() {
    local config_file=$CFG_FILE
    local config_key=$1
    local new_value=$2
    local enable=$3

    if [ ! -f "$config_file" ]; then
        alarm_and_exit "配置文件 $config_file 不存在"
    fi

    if grep -q "^#*${config_key}" "$config_file"; then
        if [ "$enable" == "enable" ]; then
            sed -i "s|^#*${config_key}.*|${config_key} ${new_value}|" "$config_file" || alarm_and_exit "更新 ${config_key} 配置失败"
        elif [ "$enable" == "disable" ]; then
            sed -i "s|^#*${config_key}.*|#${config_key} ${new_value}|" "$config_file" || alarm_and_exit "更新 ${config_key} 配置失败"
        else
            alarm_and_exit "无效的 enable 参数：$enable。有效值为 'enable' 或 'disable'。"
        fi
    else
        if [ "$enable" == "enable" ]; then
            echo "${config_key} ${new_value}" >> "$config_file" || alarm_and_exit "写入 ${config_key} 配置失败"
        elif [ "$enable" == "disable" ]; then
            echo "#${config_key} ${new_value}" >> "$config_file" || alarm_and_exit "写入 ${config_key} 配置失败"
        else
            alarm_and_exit "无效的 enable 参数：$enable。有效值为 'enable' 或 'disable'。"
        fi
    fi
}

update_ui_config() {
    local enable_ui="enable"
    if [ "${smartdns_ui_enabled}" == "true" ]; then
        enable_ui="enable"
    else
        enable_ui="disable"
    fi
    log_msg "设置使用WebUI: ${enable_ui}"
    log_msg "设置UI插件: ${TRIM_APPDEST}/bin/smartdns_ui.so"
    update_config "plugin" "${TRIM_APPDEST}/bin/smartdns_ui.so" "${enable_ui}" || alarm_and_exit "更新 plugin 配置失败"
    chmod 777 "${TRIM_APPDEST}/bin/smartdns_ui.so" || alarm_and_exit "设置 UI 插件执行权限失败"
    
    log_msg "设置UI前端目录: ${TRIM_APPDEST}/bin/wwwroot"
    update_config "smartdns-ui.www-root" "${TRIM_APPDEST}/bin/wwwroot" "enable"
    # 必须有权限读取
    chmod -R a+r "${TRIM_APPDEST}/bin/wwwroot" || alarm_and_exit "设置 UI 前端目录读取权限失败"

    log_msg "设置WebUI端口: ${smartdns_ui_port}"
    update_config "smartdns-ui.ip" "http://[::]:${smartdns_ui_port}" "${enable_ui}" || alarm_and_exit "更新 smartdns-ui.ip 配置失败"

    log_msg "设置WebUI账号: ${smartdns_ui_user}"
    update_config "smartdns-ui.user" "${smartdns_ui_user}" "${enable_ui}" || alarm_and_exit "更新 smartdns-ui.user 配置失败"

    log_msg "设置WebUI密码: ${smartdns_ui_password}"
    update_config "smartdns-ui.password" "${smartdns_ui_password}" "${enable_ui}" || alarm_and_exit "更新 smartdns-ui.password 配置失败"
}

update_ad_config() {
    local enable_ad="enable"
    if [ "${smartdns_ad_enable}" == "true" ]; then
        enable_ad="enable"
        # 下载最新屏蔽广告规则 
        # https://anti-ad.net/anti-ad-for-smartdns.conf
        wget -O "${SHARE_DIR}/ad-anti-ad-for-smartdns.conf" https://anti-ad.net/anti-ad-for-smartdns.conf || alarm_and_exit "下载广告规则失败，地址:https://anti-ad.net/anti-ad-for-smartdns.conf"
        log_msg "下载广告规则成功，地址:https://anti-ad.net/anti-ad-for-smartdns.conf"
        # https://adrules.top/smart-dns.conf
        wget -O "${SHARE_DIR}/ad-smart-dns.conf" https://adrules.top/smart-dns.conf || alarm_and_exit "下载广告规则失败,地址:https://adrules.top/smart-dns.conf"
        log_msg "下载广告规则成功，地址:https://adrules.top/smart-dns.conf"
        # https://neodev.team/smartdns.conf
        wget -O "${SHARE_DIR}/ad-smartdns.conf" https://neodev.team/smartdns.conf || alarm_and_exit "下载广告规则失败,地址:https://neodev.team/smartdns.conf"
        log_msg "下载广告规则成功，地址:https://neodev.team/smartdns.conf"
    else
        enable_ad="disable"
    fi
    log_msg "设置启用广告屏蔽: ${enable_ad}"
    update_config "conf-file" "ad-*.conf" "${enable_ad}" || alarm_and_exit "更新 smartdns-ad.conf 配置失败"
}