#!/bin/bash

### This script is called after the user installs the application.

source "$(dirname ${BASH_SOURCE[0]})/common"

ensure_exists_cfg_file() {
    if [ ! -f "${CFG_FILE}" ]; then
        mkdir -p "$(dirname ${CFG_FILE})" >> "${LOG_FILE}" 2>&1 || alarm_and_exit "无法创建配置文件目录: $(dirname ${CFG_FILE})"
        log_msg "创建配置文件目录: $(dirname ${CFG_FILE})"
        cp -f "${TRIM_APPDEST}/bin/smartdns.conf" "${CFG_FILE}" >> "${LOG_FILE}" 2>&1 || alarm_and_exit "无法拷贝默认配置到: ${CFG_FILE}"
        log_msg "配置文件不存在，拷贝默认配置到: ${CFG_FILE}"
    fi
}

unpack_bin() {
    local bin_dir="${TRIM_APPDEST}/bin"
    local pack_file="${TRIM_APPDEST}/bin.tar.gz"
    if [ -f "${pack_file}" ]; then
        log_msg "解压应用文件"
        bash -c "rm -rf ${bin_dir}" 2>&1
        bash -c "mkdir -p ${bin_dir}" 2>&1
        bash -c "tar -xzvf ${pack_file} -C ${bin_dir}" 2>&1 || alarm_and_exit "无法解压应用二进制文件"
        bash -c "rm -f ${pack_file}" 2>&1
        log_msg "解压应用二进制文件完成"
    else
        alarm_and_exit "应用二进制文件压缩包不存在: ${pack_file}"
    fi
}

unpack_bin
ensure_exists_cfg_file
# 设置日志文件路径、缓存文件路径 到应用专属动态数据目录
update_config "data-dir" "${DATA_DIR}" "enable"
log_msg "设置数据目录: ${DATA_DIR}"
mkdir -p "${DATA_DIR}/cache" >> "${LOG_FILE}" 2>&1 || alarm_and_exit "无法创建数据目录: ${DATA_DIR}/cache"
log_msg "创建缓存目录: ${DATA_DIR}/cache"
update_config "cache-file" "${DATA_DIR}/cache/smartdns.cache" "enable"
log_msg "设置缓存路径: ${DATA_DIR}/cache/smartdns.cache"
update_config "log-file" "${LOG_DIR}/smartdns.log" "enable"
log_msg "设置日志路径: ${LOG_DIR}/smartdns.log"

if [ -n "${wizard_enable_config}" ] && [ "${wizard_enable_config}" = "true" ]; then
    log_msg "启用向导配置，覆盖配置文件"
    # 向导配置覆盖安装后默认配置
    # 设置监听端口
    update_config "log-level" "${smartdns_log_level}" "enable"
    log_msg "设置日志级别: ${smartdns_log_level}"
    update_config "bind" "[::]:${smartdns_dns_port}" "enable"
    log_msg "设置DNS监听端口: ${smartdns_dns_port}"
    update_ad_config
    update_ui_config
else
    log_msg "不启用向导配置，保持原有配置文件不变"
fi

exit 0